[workspace]
authors = ["Bing.Guo <bing.guo@som.umaryland.edu>"]
channels = ["conda-forge", "bioconda"]
name = "snpeff_annot"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
snpeff_annot = "./snpfeff_annot.py"

[dependencies]
snpeff = ">=5.4.0c,<6"
pandas = ">=3.0.5,<4"
bcftools = ">=1.24,<2"
ruff = ">=0.16.7,<0.17"
ty = ">=0.0.80,<0.0.81"
wget = ">=1.25.0,<2"

[feature.dev.dependencies]
ipython = "*"

[environments]
dev = ["dev", "default"]
